### ISSUE TITLE
Error installing AAL Studio plugin

### ISSUE THREAD

**Issue by ghost** [universAAL/tools.eclipse-plugins#438]
Hello,

I am a member of the development team Universidade Estadual da Paraíba (UEPB) located in Brazil.
    Our team started studying universAAL and during the installation process of the AAL Studio plugin some problems have arisen. First, the repository link could [not be found](https://drive.google.com/open?id=0B2q1FzhNQIRoeUxMYXEtVUp5d3M) so we removed the part that indicates the version in the url. Therefore, it was possible to install some plugins ([plugins not installed](https://drive.google.com/open?id=0B2q1FzhNQIRoZnJmNkE3WklLNWM)). Then we tried to execute the "Hello World" available in the documentation, but the part of "run configurations" could not be done because the [following error appears](https://drive.google.com/open?id=0B2q1FzhNQIRoWXo2NVJ2S1E0TXc). Moreover, we could not build the project. Finally, when we tried to create a new uAAL Run config the following error [appears](https://drive.google.com/open?id=0B2q1FzhNQIRoZVJoT0RrZHh2R28) and Eclipse crashes.

We have tried two ways to solve this issue: Firstly, we tried to solve using an old version of the Eclipse (Indigo), which we could install the plugin without any "Will not be installed" but when performing the step of the image ([see image](https://raw.githubusercontent.com/wiki/universAAL/platform/RD_020.png)) a project and add to the list of direct packages on the right side to be started automatically using the corresponding button [this message](https://drive.google.com/open?id=0B2q1FzhNQIRoY0ZYaTBpSTBZZjA) appears and clicking on run it gives the following error message ([here](https://drive.google.com/open?id=0B2q1FzhNQIRoY3U1Ry1KbVhjV0E)); Lastly, we tried to solve (using the Neon 3 eclipse version) and removing the Modeling tools and the OWL to UML transformations from the installation but the same error persisted.

We use the following settings:

First scenario:
- Eclipse Indigo Release (3.7.2)
- JDK 1.7.0_80

Last scenario:
- Eclipse Neon.3 Release (4.6.3)
- JDK 1.8.0_1.3.1

**Comment by Alfiva** [comment]
Hello Edson,
Can you paste the links to the instructions you have followed?

**Comment by ghost** [comment]
Hi, @Alfiva 

I followed the instructions provided by the documentation of the Universaal website ([here](https://github.com/universAAL/platform/wiki)).

In the first scenario the error occurs when we perform these steps [here](https://github.com/universAAL/platform/wiki/Running-with-Eclipse-and-Pax-Runner-%28Details%29). In this case the difficulty is in installing the AAL Studio plugin

Already in the second scenario when we performed these steps [here](https://github.com/universAAL/platform/wiki/Development-environment-setup-%28Details%29). In this case we were able to install the plugin but when we try to run "Hello world" it gives the following error: [image](https://drive.google.com/open?id=0B2q1FzhNQIRoY3U1Ry1KbVhjV0E).

**Comment by Alfiva** [comment]
Unfortunately I am not used to the Pax Runner execution method described there. Other developers may join the conversation and provide support here...
In the meantime, I can suggest you to use the Karaf execution method described here: https://github.com/universAAL/platform/wiki/Running-with-Apache-Karaf-%28Details%29 
With this you will skip the AAL Studio and the embedded runner, using a Karaf container that is closer to what you will actually run in the end, not just for developing.
Let me know if you find any issue with that (I'm going to fix a couple typos in that page that I just found).

**Comment by cstockloew** [comment]
I just uploaded a new version of the tools, please
Install Eclipse Modelling Tools version 4.6 (Neon)
Install Eclipse Plugins from http://depot.universaal.org/eclipse-update/4.6/
