### ISSUE TITLE
Error creating new project: Could not create initial files or edit POM!

### ISSUE THREAD

**Issue by softwareEngineersOrg** [universAAL/tools.eclipse-plugins#444]
Hi, 

I have some problem with create a new ontology project in universAAL studio.

I try to initiate the project by using option in menu "Menu>universAAL>Create a new ontology project". After that I receive message "Problem Occured 'Shaping new universAAL project' has encountered a problem. Cannot modify resource set without a write transaction". 
In details there are the same message "Cannot modify resource set without a write transaction".

Please help me!

Artur

**Comment by Alfiva** [comment]
The universAAL Studio plugins haven't been updated in a while, it may be possible that an update to Eclipse has made some code incompatible... I have tried with Eclipse Neon 3 (4.6.3) and it works OK, but not sure when we'll have time to review up to which version it is supported and how and when to update it.
In the meantime, I suggest you either use an older version of Eclipse (sorry) like that one, or create the ontology manually - although in the latter case you lose the graphical modeling tools.
To create an ontology manually, you can follow these instructions: https://github.com/universAAL/ontology/wiki/Guidelines
https://github.com/universAAL/platform/wiki/Ontologies-%28Quick%29
https://github.com/universAAL/platform/wiki/Ontologies-%28Details%29
or just copy/paste an example ontology and change it to your needs, like the one in https://github.com/universAAL/samples/tree/master/ont.tutorial

**Comment by softwareEngineersOrg** [comment]
Thank you! I install Modelling Tools under Eclipse Neon 3 (4.6.3) and plugin http://depot.universaal.org/eclipse-update/4.6. This function works!
--
Best Regards,
Artur
