### ISSUE TITLE
http://depot.universaal.org/ is not reachable

### ISSUE THREAD

**Issue by laughingZebra** [universAAL/tools.eclipse-plugins#446]
Hi,

It seems the http://depot.universaal.org/ is not reachable.
Are you still supporting the project?

Best Regards,
LZ

**Comment by Alfiva** [comment]
Thanks for pointing this out. We are currently re-structuring some of the websites and getting rid of some that are no longer used, and it may have some side effects. I'm not sure when we will have everything back in place, we will do our best to maintain the platform available for everyone.

**Comment by saiedt** [comment]
The issue with depot.universaal.org has finally been resolved!
We are so sorry for the long delay...
